language: python

python:
  - 3.5

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pep8

script:
  - coverage run --omit=*.virtualenvs*,*virtualenv* django/santropolFeast/manage.py test --settings=santropolFeast.settings_test member meal order notification delivery note billing
  - pep8 --count --show-source --exclude=migrations django/santropolFeast/

after_success:
  - coveralls
