version: '2'
services:
  db:
    image: postgres
    environment:
        POSTGRES_DB: feast
  web:
    build: .
    command: python django/santropolFeast/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
