# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 02:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_client_delivery_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='meal_default_week',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
