# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_client_delivery_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_scheduled_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=1)),
                ('to_status', models.CharField(max_length=1)),
                ('change_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('change_state', models.CharField(choices=[('alone', 'Alone'), ('start', 'Start'), ('end', 'End')], max_length=5)),
                ('processed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Client')),
                ('linked_scheduled_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Client_scheduled_status')),
            ],
        ),
    ]
